lighthouse:
  checksum: sha256:23e898614d370f16144f5f3c8f3d3e387fed10caa17bad2bb24395d76f18cbc9
  version: v3.0.0

configuration:
  lighthouse:
    network: "mainnet"
    datadir_base: "/home/lighthouse/.lighthouse"
    graffiti: null
    log_level: info
    validator:
      enable_doppleganger_protection: true
    beacon:
      target_peers: 50
    slasher:
      enabled: false
      broadcast: false
      datadir: datadir_base/network/beacon/slash_db
      # this is in GB
      max_database_size: 256
