lighthouse:
  checksum: sha256:d459eb81f40a125dd92ff95f96ad642b4f4b1f65168844022d7e19b486e1cfc1
  version: v2.3.1

configuration:
  lighthouse:
    network: "mainnet"
    datadir_base: "/home/lighthouse/.lighthouse"
    graffiti: null
    log_level: info
    validator:
      enable_doppleganger_protection: true
    beacon:
      eth1_endpoints:
        - http://localhost:8545
      target_peers: 50
    slasher:
      enabled: false
      broadcast: false
      datadir: datadir_base/network/beacon/slash_db
      # this is in GB
      max_database_size: 256
