lighthouse:
  checksum: sha256:1a118a08387b1f5ebd342fe8a38ac5db322a236c42c3b2183de02bed7826205c
  version: v1.3.0

configuration:
  lighthouse:
    network: "mainnet"
    datadir_base: "/home/lighthouse/.lighthouse"
    graffiti: null
    log_level: info
    beacon:
      eth1_endpoints:
        - http://localhost:8545
      target_peers: 50
    slasher:
      enabled: false
      broadcast: false
      datadir: datadir_base/network/beacon/slash_db
      # this is in GB
      max_database_size: 256
