packages:
  apt:
    monitoring:
      - prometheus
      - prometheus-alertmanager
  snap:
    monitoring:
      - grafana

configuration:
  prometheus:
    storage:
      path: null
      retention: null
  alertmanager:
    receivers: []
