- name: Restart beacon
  ansible.builtin.systemd:
    name: beacon
    daemon_reload: true
    state: restarted
  become: true

- name: Restart validator
  ansible.builtin.systemd:
    name: validator
    daemon_reload: true
    state: restarted
  become: true
