- hosts: all
  roles:
    - packages
    - system
- hosts: mevbroker
  roles:
    - role: mevboost
      when: ( mevboost.enable | default(false) ) == true
- hosts: execution
  roles:
    - geth
- hosts: beacon
  roles:
    - lighthouse
- hosts: validator
  roles:
    - lighthouse
- hosts: monitoring
  roles:
    - monitoring
