- name: Install apt repositories
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
  with_items: "{{ packages.apt_repositories.values() | flatten | sort | unique | default([]) }}"

- name: Update package index
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade all packages
  become: true
  ansible.builtin.apt:
    name: "*"
    update_cache: true
    state: latest
    force_apt_get: true

- name: Install packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages.apt.values() | flatten | sort | unique | default([]) }}"
    state: present

- name: Freeze select packages
  become: true
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items: "{{ packages.apt_hold | flatten | default([]) }}"

- name: Install snaps
  become: true
  shell:
    cmd: "snap install {{ item }}"
  changed_when: false
  loop: "{{ packages.snap.values() | flatten | sort | unique | default([]) }}"
