- name: Create mevboost group
  ansible.builtin.group:
    name: mevboost
    state: present
  become: true

- name: Create mevboost user
  ansible.builtin.user:
    name: mevboost
    groups: mevboost
    shell: /usr/sbin/nologin
  become: true

- name: Restrict mevboost home directory permissions
  ansible.builtin.file:
    path: /home/mevboost
    state: directory
    owner: mevboost
    group: mevboost
    mode: '0750'
  become: true

- name: Create directory for mev-boost binary
  ansible.builtin.file:
        path: /home/mevboost/bin
        state: directory
        owner: mevboost
        group: mevboost
        mode: '0750'
  become: true


- name: Install mev-boost via GH artifact
  when: configuration.mevboost.method == "gh-artifact"
  block:
    - name: Download mevboost GH artifact
      ansible.builtin.get_url:
        url: https://github.com/flashbots/mev-boost/releases/download/v{{ configuration.mevboost.version }}/mev-boost_{{ configuration.mevboost.version }}_linux_amd64.tar.gz
        dest: /home/mevboost/mevboost-{{ configuration.mevboost.version }}.tgz
        owner: mevboost
        group: mevboost
        mode: '0644'
      register: mevboost_download
      become: true

    - name: Extract mevboost binary
      ansible.builtin.unarchive:
        src: /home/mevboost/mevboost-{{ configuration.mevboost.version }}.tgz
        dest: /home/mevboost/bin/
        remote_src: true
      when: mevboost_download.changed
      become: true
      notify:
        - Restart mevboost

    - name: Ensure correct mevboost binary permissions
      ansible.builtin.file:
        path: /home/mevboost/bin/mev-boost
        state: file
        owner: mevboost
        group: mevboost
        mode: '0700'
      become: true

# This will require local installations of Go 1.18+ and support cGo
- name: Install mev-boost via Go
  when: configuration.mevboost.method == "go-install"
  block:
    - name: Install mev-boost
      ansible.builtin.command:
        argv:
          - go
          - install
          - github.com/flashbots/mev-boost@{{ configuration.mevboost.version | default('latest') }}
      notify: Restart mevboost

    - name: Get GOBIN value
      ansible.builtin.command:
        argv:
          - go
          - env
          - GOBIN
      register: gobin
    - name: Get GOPATH value
      ansible.builtin.command:
        argv:
          - go
          - env
          - GOPATH
      register: gopath
    - name: Set install home
      ansible.builtin.set_fact:
        mevboost_bindir: "{{ gobin.stdout | default((gopath.stdout | trim) ~ '/bin', true) }}"
    - name: Copy mev-boost binary
      ansible.builtin.copy:
        src: "{{ mevboost_bindir }}/mev-boost"
        dest: "/home/mevboost/bin/mev-boost"
        owner: mevboost
        group: mevboost
        mode: '0700'
      become: true

- name: Configure mevboost systemd unit
  ansible.builtin.template:
    src: mevboost.service.j2
    dest: /etc/systemd/system/mevboost.service
    owner: root
    group: root
    mode: '0664'
  become: true
  notify: Restart mevboost

- name: Enable mevboost systemd unit
  ansible.builtin.systemd:
    name: mevboost
    daemon_reload: true
    state: started
    enabled: true
    masked: false
  become: true

