- name: Configure Prometheus
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart Prometheus

- name: Configure Prometheus Alerts
  template:
    src: prometheus-alerts.yml.j2
    dest: /etc/prometheus/alerts.yml
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart Prometheus

- name: Configure permissions on custom storage path
  file:
    path: "{{ configuration.prometheus.storage.path }}"
    owner: prometheus
    group: prometheus
    mode: '0755'
  become: true
  when: configuration.prometheus.storage.path | default(False)

- name: Customize Prometheus service
  template:
    src: prometheus.env.j2
    dest: /etc/default/prometheus
    owner: root
    group: root
    mode: '0644'
  become: true
  when: configuration.prometheus.storage.path | default(False) or
        configuration.prometheus.storage.retention | default(False)
  notify: Restart Prometheus

- name: Configure Alertmanager
  template:
    src: alertmanager.yml.j2
    dest: /etc/prometheus/alertmanager.yml
    owner: prometheus
    group: root
    mode: '0600'
  become: true
  when: configuration.alertmanager.receivers | default([]) | length > 0
  notify: Restart Alertmanager

- name: Customize Alertmanager service
  template:
    src: alertmanager.env.j2
    dest: /etc/default/prometheus-alertmanager
    owner: root
    group: root
    mode: '0644'
  become: true
  when: configuration.prometheus.storage.path | default(False)
  notify: Restart Alertmanager

- name: Ensure grafana configuration directories exist
  file:
    path: /var/snap/grafana/common/{{ item }}
    state: directory
    owner: root
    group: root
    mode: '0750'
  with_items:
    - conf
    - conf/provisioning
    - conf/provisioning/dashboards
    - conf/provisioning/datasources
    - conf/provisioning/notifiers
    - dashboards
    - dashboards/geth
    - dashboards/lighthouse
    - dashboards/node
    - staging
    - staging/lighthouse
    - staging/lighthouse/dashboards
    - staging/lighthouse/dashboards/final
    - staging/lighthouse/dashboards/raw
  become: true

- name: Configure Grafana
  copy:
    src: grafana/custom.ini
    dest: /var/snap/grafana/common/conf/custom.ini
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart Grafana

- name: Copy Grafana dashboards for Lighthouse
  include_tasks: install_lighthouse_dashboard.yaml
  with_fileglob:
    - '{{ playbook_dir }}/vendor/lighthouse-metrics/dashboards/*.json'

- name: Copy Grafana dashboards for Geth
  copy:
    src: '{{ item }}'
    dest: /var/snap/grafana/common/dashboards/geth/{{ item | basename }}
    owner: root
    group: root
    mode: '0644'
  with_fileglob:
    - '{{ playbook_dir }}/roles/monitoring/files/grafana/dashboards/geth/*.json'
  become: true
  notify: Restart Grafana

- name: Copy Grafana dashboards for Node
  copy:
    src: '{{ item }}'
    dest: /var/snap/grafana/common/dashboards/node/{{ item | basename }}
    owner: root
    group: root
    mode: '0644'
  with_fileglob:
    - '{{ playbook_dir }}/roles/monitoring/files/grafana/dashboards/node/*.json'
  become: true
  notify: Restart Grafana

- name: Configure Grafana provisioning
  copy:
    src: grafana/provisioning/{{ item }}
    dest: /var/snap/grafana/common/conf/provisioning/{{ item }}
    owner: root
    group: root
    mode: '0644'
  with_items:
    - dashboards/geth.yaml
    - dashboards/lighthouse.yaml
    - dashboards/node.yaml
    - datasources/prometheus.yaml
  become: true
  notify: Restart Grafana
