- name: Create geth group
  group:
    name: geth
    state: present
  become: true

- name: Create geth user
  user:
    name: geth
    groups: geth
    shell: /usr/sbin/nologin
  become: true

- name: Restrict geth home directory permissions
  file:
    path: /home/geth
    state: directory
    owner: geth
    group: geth
    mode: '0750'
  become: true

- name: Configure geth
  template:
    src: geth.toml.j2
    dest:  "{{ configuration.geth.path }}"
    owner: geth
    group: geth
    mode: '0644'
  become: true

- name: Set data directory permissions
  file:
    path: "{{ configuration.geth.node.datadir }}"
    state: directory
    owner: geth
    group: geth
    mode: '0750'
  become: true

- name: Configure systemd unit
  template:
    src: geth.service.j2
    dest: /etc/systemd/system/geth.service
    owner: root
    group: root
    mode: '0664'
  become: true
  notify: Restart geth

- name: Enable geth service
  systemd:
    name: geth
    state: started
    enabled: true
  become: true
